//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("govnocode.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не подтвержден либо другая ошибка.
        /// </summary>
        public static string AccountController_Login_Email_не_подтвержден_либо_другая_ошибка {
            get {
                return ResourceManager.GetString("AccountController_Login_Email_не_подтвержден_либо_другая_ошибка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string AccountController_Login_Invalid_login_attempt_ {
            get {
                return ResourceManager.GetString("AccountController_Login_Invalid_login_attempt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вы заблокированы.
        /// </summary>
        public static string AccountController_Login_вы_заблокированы {
            get {
                return ResourceManager.GetString("AccountController_Login_вы_заблокированы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        public static string AccountController_VerifyCode_Invalid_code_ {
            get {
                return ResourceManager.GetString("AccountController_VerifyCode_Invalid_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить пользователя?.
        /// </summary>
        public static string AdminDeleteText {
            get {
                return ResourceManager.GetString("AdminDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string AdminDeleteTitle {
            get {
                return ResourceManager.GetString("AdminDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string AdminDeleteUserText {
            get {
                return ResourceManager.GetString("AdminDeleteUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список пользователей.
        /// </summary>
        public static string AdminIndex {
            get {
                return ResourceManager.GetString("AdminIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться к списку.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заблокирован.
        /// </summary>
        public static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К публикации.
        /// </summary>
        public static string BtnToPublication {
            get {
                return ResourceManager.GetString("BtnToPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление паролем.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форма для изменения пароля.
        /// </summary>
        public static string ChangePassForm {
            get {
                return ResourceManager.GetString("ChangePassForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользовательскими данными.
        /// </summary>
        public static string ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Листинг.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение почты.
        /// </summary>
        public static string ComfimEmailTitle {
            get {
                return ResourceManager.GetString("ComfimEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за подтверждения вашей почты. Пожалуйста .
        /// </summary>
        public static string ConfimEmailText {
            get {
                return ResourceManager.GetString("ConfimEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите для входа.
        /// </summary>
        public static string ConfimEmailTextLink {
            get {
                return ResourceManager.GetString("ConfimEmailTextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение вашего аккаунта.
        /// </summary>
        public static string Confirm_your_account {
            get {
                return ResourceManager.GetString("Confirm_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связь.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание профиля.
        /// </summary>
        public static string CreateLocalLogin {
            get {
                return ResourceManager.GetString("CreateLocalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать.
        /// </summary>
        public static string CreatePost {
            get {
                return ResourceManager.GetString("CreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глянуть.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string drrf {
            get {
                return ResourceManager.GetString("drrf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование комментария.
        /// </summary>
        public static string EditComment {
            get {
                return ResourceManager.GetString("EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новое имя.
        /// </summary>
        public static string EnterNewName {
            get {
                return ResourceManager.GetString("EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не имеете профиля на этом сайте..
        /// </summary>
        public static string ErrorPass {
            get {
                return ResourceManager.GetString("ErrorPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить ссылку.
        /// </summary>
        public static string ForgotPassBtnText {
            get {
                return ResourceManager.GetString("ForgotPassBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите свой email.
        /// </summary>
        public static string ForgotPassEnterYourEmail {
            get {
                return ResourceManager.GetString("ForgotPassEnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста проверьте свой email для восстановления пароля..
        /// </summary>
        public static string ForgotPassText {
            get {
                return ResourceManager.GetString("ForgotPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string ForgotPassTitle {
            get {
                return ResourceManager.GetString("ForgotPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        public static string ForgotPassTitle2 {
            get {
                return ResourceManager.GetString("ForgotPassTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to тут.
        /// </summary>
        public static string here {
            get {
                return ResourceManager.GetString("here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в теме:.
        /// </summary>
        public static string InPublication {
            get {
                return ResourceManager.GetString("InPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Только ссылку на фото.
        /// </summary>
        public static string Link_Image {
            get {
                return ResourceManager.GetString("Link_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginBtnLogin {
            get {
                return ResourceManager.GetString("LoginBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LoginPass {
            get {
                return ResourceManager.GetString("LoginPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string LoginRegisterForgoutPass {
            get {
                return ResourceManager.GetString("LoginRegisterForgoutPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать нового пользователя.
        /// </summary>
        public static string LoginRegisterNewUser {
            get {
                return ResourceManager.GetString("LoginRegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используйте свой логин для входа.
        /// </summary>
        public static string LoginUseLogin {
            get {
                return ResourceManager.GetString("LoginUseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мои публикации.
        /// </summary>
        public static string MyPublication {
            get {
                return ResourceManager.GetString("MyPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имя уже используется.
        /// </summary>
        public static string name_already {
            get {
                return ResourceManager.GetString("name_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мега проект.
        /// </summary>
        public static string NameProject {
            get {
                return ResourceManager.GetString("NameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новее.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старее.
        /// </summary>
        public static string Old {
            get {
                return ResourceManager.GetString("Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для подтверждения email нажмите.
        /// </summary>
        public static string Please_confirm_your_account_by_clicking {
            get {
                return ResourceManager.GetString("Please_confirm_your_account_by_clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для сброса пароля нажмите .
        /// </summary>
        public static string Please_reset_your_password_by_clicking {
            get {
                return ResourceManager.GetString("Please_reset_your_password_by_clicking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикация.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикации.
        /// </summary>
        public static string Publications {
            get {
                return ResourceManager.GetString("Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового профиля.
        /// </summary>
        public static string RegisterCreateNewAccount {
            get {
                return ResourceManager.GetString("RegisterCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterRegister {
            get {
                return ResourceManager.GetString("RegisterRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешная регистрация.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте свою почту.
        /// </summary>
        public static string RegisterSuccessCheckEmail {
            get {
                return ResourceManager.GetString("RegisterSuccessCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string ResetBtnReset {
            get {
                return ResourceManager.GetString("ResetBtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль сброшен..
        /// </summary>
        public static string ResetPassConfimationText {
            get {
                return ResourceManager.GetString("ResetPassConfimationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassConfimationTitle {
            get {
                return ResourceManager.GetString("ResetPassConfimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassTitle {
            get {
                return ResourceManager.GetString("ResetPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изменения сохранены.
        /// </summary>
        public static string save_changes {
            get {
                return ResourceManager.GetString("save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено комментариев.
        /// </summary>
        public static string SearchComments {
            get {
                return ResourceManager.GetString("SearchComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено публикаций.
        /// </summary>
        public static string SearchPublication {
            get {
                return ResourceManager.GetString("SearchPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Теги.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        public static string tg {
            get {
                return ResourceManager.GetString("tg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скин сайта.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ комментариев.
        /// </summary>
        public static string Top5comments {
            get {
                return ResourceManager.GetString("Top5comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ C#.
        /// </summary>
        public static string Top5CSharp {
            get {
                return ResourceManager.GetString("Top5CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ Java.
        /// </summary>
        public static string Top5Java {
            get {
                return ResourceManager.GetString("Top5Java", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ Публикаций .
        /// </summary>
        public static string Top5Posts {
            get {
                return ResourceManager.GetString("Top5Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ Python.
        /// </summary>
        public static string Top5Python {
            get {
                return ResourceManager.GetString("Top5Python", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ  Ruby.
        /// </summary>
        public static string Top5Ruby {
            get {
                return ResourceManager.GetString("Top5Ruby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ Пользователей.
        /// </summary>
        public static string Top5Users {
            get {
                return ResourceManager.GetString("Top5Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топ по сайту.
        /// </summary>
        public static string TopAll {
            get {
                return ResourceManager.GetString("TopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
