//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("govnocode.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение почты.
        /// </summary>
        public static string ComfimEmailTitle {
            get {
                return ResourceManager.GetString("ComfimEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за подтверждения вашей почты. Пожалуйста .
        /// </summary>
        public static string ConfimEmailText {
            get {
                return ResourceManager.GetString("ConfimEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите для входа.
        /// </summary>
        public static string ConfimEmailTextLink {
            get {
                return ResourceManager.GetString("ConfimEmailTextLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить ссылку.
        /// </summary>
        public static string ForgotPassBtnText {
            get {
                return ResourceManager.GetString("ForgotPassBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите свой email.
        /// </summary>
        public static string ForgotPassEnterYourEmail {
            get {
                return ResourceManager.GetString("ForgotPassEnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста проверьте свой email для восстановления пароля..
        /// </summary>
        public static string ForgotPassText {
            get {
                return ResourceManager.GetString("ForgotPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string ForgotPassTitle {
            get {
                return ResourceManager.GetString("ForgotPassTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановление пароля.
        /// </summary>
        public static string ForgotPassTitle2 {
            get {
                return ResourceManager.GetString("ForgotPassTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginBtnLogin {
            get {
                return ResourceManager.GetString("LoginBtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string LoginPass {
            get {
                return ResourceManager.GetString("LoginPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забыли пароль?.
        /// </summary>
        public static string LoginRegisterForgoutPass {
            get {
                return ResourceManager.GetString("LoginRegisterForgoutPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать нового пользователя.
        /// </summary>
        public static string LoginRegisterNewUser {
            get {
                return ResourceManager.GetString("LoginRegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используйте свой логин для входа.
        /// </summary>
        public static string LoginUseLogin {
            get {
                return ResourceManager.GetString("LoginUseLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание нового профиля.
        /// </summary>
        public static string RegisterCreateNewAccount {
            get {
                return ResourceManager.GetString("RegisterCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterRegister {
            get {
                return ResourceManager.GetString("RegisterRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешная регистрация.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверьте свою почту.
        /// </summary>
        public static string RegisterSuccessCheckEmail {
            get {
                return ResourceManager.GetString("RegisterSuccessCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string ResetBtnReset {
            get {
                return ResourceManager.GetString("ResetBtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пароль сброшен..
        /// </summary>
        public static string ResetPassConfimationText {
            get {
                return ResourceManager.GetString("ResetPassConfimationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassConfimationTitle {
            get {
                return ResourceManager.GetString("ResetPassConfimationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс пароля.
        /// </summary>
        public static string ResetPassTitle {
            get {
                return ResourceManager.GetString("ResetPassTitle", resourceCulture);
            }
        }
    }
}
